name: Trigger Render Backend Deploy

on:
  push:
    paths:
      - 'backend/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Call Render Deploy Hook
        run: |
          echo "Calling Render Deploy Hook"
          curl -v -X POST ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
